services:
    nginx:
        image: nginx:latest
        container_name: "nginx"
        volumes:
            - ./deploy/prod/nginx.conf:/etc/nginx/nginx.conf
            - ./deploy/prod/logs:/var/log/nginx
        ports:
            - "8080:8080"
            - "443:443" # HTTPS
        restart: unless-stopped
        mem_limit: 50m
        networks:
            - app-network
    app:
        image: tinphamtp/blitz-api:latest
        env_file:
            - .env
        entrypoint: []
        command: ["bun", "run", "build/index.js"]
        expose:
            - "9000"  # Expose only within the network
        mem_limit: 500m
        restart: always
        depends_on:
            redis:
                condition: service_healthy
        networks:
            - app-network
    redis:
        image: redis/redis-stack-server:latest
        container_name: "redis"
        volumes:
            - ./data/redis:/data
        mem_limit: 250m
        restart: always
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
            interval: 10s
            retries: 5
            start_period: 5s
            timeout: 5s
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
