services:
    api:
        build:
            context: .
            dockerfile: apps/api/Dockerfile.yml
        env_file:
            - .env
                
    worker:
        build:
            context: .
            dockerfile: apps/workers/Dockerfile.yml
        env_file:
            - .env
        