services:
    nginx:
        image: nginx:latest
        container_name: "nginx"
        volumes:
            - ./deploy/local/nginx.conf:/etc/nginx/nginx.conf
            - ./deploy/local/logs:/var/log/nginx
        ports:
            - "8080:80"
            - "443:443" # HTTPS
        restart: unless-stopped
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
            interval: 30s
            timeout: 10s
            retries: 3
    
    redis-stack:
        image: redis/redis-stack:latest
        container_name: "redis-stack"
        volumes:
            - ./data/redis:/data
        restart: always
        ports:
            - "6379:6379"
        networks:
            - app-network

    # nats:
    #     image: bitnami/nats:latest
    #     container_name: "nats"
    #     ports:
    #         - "4222:4222"
    #     restart: always
    #     healthcheck:
    #         test: ["CMD", "nc", "-z", "localhost", "4222"]
    #         interval: 20s
    #         timeout: 5s
    #         retries: 3
    #     networks:
    #         - app-network

networks:
    app-network:
        driver: bridge
        