services:
    app:
        image: tinphamtp/blitz-api:latest
        build:
            context: .
            dockerfile: Dockerfile

        env_file:
            - .env

        # override default entrypoint allows us to do `bun install` before serving
        entrypoint: []

        # execute bun install before we start the dev server in watch mode
        command: ["bun", "run", "src/index.ts"]

        # expose the right ports
        ports: ["9000:8000"]

        mem_limit: 500m
        restart: always

        depends_on:
            redis:
                condition: service_healthy
        networks:
            - app-network

    redis:
        image: redis/redis-stack-server:latest
        container_name: "redis"
        volumes:
            - ./data/redis:/data

        mem_limit: 250m
        restart: always

        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
            interval: 10s
            retries: 5
            start_period: 5s
            timeout: 5s
        networks:
            - app-network

networks:
    app-network: # Create a network called 'app-network'
        driver: bridge
