FROM oven/bun

WORKDIR /app

# Copy dependency files first for better caching
COPY package.json .

COPY tsconfig.json .

COPY .env.local .env

COPY apps/shared/package.json apps/shared/package.json

COPY apps/api/package.json apps/api/package.json

COPY apps/workers/package.json apps/workers/package.json

# Install dependencies (faster layer caching)
RUN bun install

# Copy the rest of the code
COPY apps/shared apps/shared

COPY apps/api apps/api

COPY apps/workers apps/workers

WORKDIR /app/apps/workers

ENV BUN_ENV=development

CMD ["bun", "run", "--title=kamdo-worker", "index.ts"]
