FROM oven/bun AS builder

WORKDIR /app

COPY package.json .
COPY tsconfig.json .

COPY apps/shared apps/shared
COPY apps/api apps/api
COPY apps/workers apps/workers
COPY .env .env

WORKDIR /app/apps/workers

RUN bun install

RUN bun build ./index.ts --target bun --outdir ./build --minify

# Runtime stage
FROM oven/bun:slim

COPY --from=builder /app/apps/workers/build ./build
COPY --from=builder /app/apps/workers ./workers 
COPY --from=builder /app/.env .env 

ENV BUN_ENV=production

CMD ["bun", "run", "./build/index.js"]