FROM oven/bun

WORKDIR /app

# Copy dependency files first for better caching
COPY package.json .

COPY tsconfig.json .

COPY .env.local .env

COPY apps/shared/package.json apps/shared/package.json

COPY apps/api/package.json apps/api/package.json

# Install dependencies (faster layer caching)
RUN bun install --frozen-lockfile

COPY apps/shared apps/shared

COPY apps/api apps/api

WORKDIR /app/apps/api

ENV BUN_ENV=development

CMD ["bun", "run", "--title=kamdo-api", "index.ts"]

EXPOSE 8000