# Stage 1: Build
FROM oven/bun:alpine AS builder

WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY apps/shared apps/shared
COPY apps/api apps/api
COPY .env .env

WORKDIR /app/apps/api

RUN bun install
RUN bun build ./index.ts --target bun --outdir ./build --minify

RUN rm -rf node_modules
RUN rm -rf bun.lockb
RUN rm -rf tsconfig.json
RUN rm -rf apps/shared

# Stage 2: Runtime
FROM oven/bun:alpine

WORKDIR /app/apps/api

# Copy only the necessary files from the builder stage
COPY --from=builder /app/apps/api/build ./build 
COPY --from=builder /app/.env ../../.env

ENV BUN_ENV=production

CMD ["bun", "run", "./build/index.js"]

EXPOSE 8000
